/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaranch13;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Piet
 */
public class JoritNeugebauer {

    static JTextArea name;
    static JTextField attribut;
    static JTextField methode;
    static JPanel panel;
    static JFrame frame;
    static JButton button;

    public static void main(String... args) {
        frame = new JFrame();
        panel = new JPanel();
        button = new JButton("Jorit");
        button.addActionListener(actionEvent -> jButton1ActionPerformed(actionEvent));
        panel.add(button);
        frame.add(panel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    private static void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        name = new JTextArea();
        name.append("This is some text!");
        name.setBounds(100, 170, 380, 350);
        attribut = new JTextField(10);
        attribut.setBounds(100, 170, 380, 370);
        methode = new JTextField(10);
        methode.setBounds(100, 170, 380, 370);

        panel.add(name);
        panel.add(attribut);
        panel.add(methode);
        frame.pack();
    }
}

class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public JTextArea name;
    public JTextField attribut, methode;
    public boolean adderPressed;

    public MainWindow() {
        initComponents();
        jCheckBox1.setSelected(true);
        jCheckBox2.setSelected(true);
        adderPressed = false;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(800, 600));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("add class");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jCheckBox1.setText("class visible");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jCheckBox2.setText("method visible");
        jCheckBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox2ItemStateChanged(evt);
            }
        });
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        jButton2.setText("save");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        jButton3.setText("print");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>                        

    private void formKeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {
//
    }

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {
        if (jCheckBox1.isSelected()) {
            if (adderPressed) {
                name.setVisible(true);
                attribut.setVisible(true);
                methode.setVisible(true);
            }
            System.out.println("Klassen sichtbar gemacht.");
        } else {
            jCheckBox2.setSelected(false);
            if (adderPressed) {
                name.setVisible(false);
                attribut.setVisible(false);
            }
            System.out.println("Klassen unsichtbar gemacht.");
        }
    }

    private void jCheckBox2ItemStateChanged(java.awt.event.ItemEvent evt) {

        if (jCheckBox2.isSelected()) {
            jCheckBox1.setSelected(true);
            if (adderPressed) {
            }
            System.out.println("Methoden sichtbar gemacht.");
        } else {
            if (adderPressed) {
                methode.setVisible(false);
                System.out.println("Methoden unsichtbar gemacht.");
            }
        }
    }

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {
        System.err.println("Speichern nicht möglich!");
    }

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {
        System.err.println("Das kann noch nicht gedruckt werden!");
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        name = new JTextArea(20, 20);
        name.setText("Klassendiagramm");
        name.setBounds(400, 270, 180, 150);
        attribut = new JTextField(10);
        attribut.setBounds(500, 300, 180, 170);
        attribut.setText("attribut");
        methode = new JTextField(10);
        methode.setBounds(600, 330, 80, 70);
        methode.setText("methode");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 80, 50));
        jPanel1.add(attribut, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 80, 70));
        jPanel1.add(methode, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 80, 70));

//        jPanel1.add(name);
//        jPanel1.add(attribut);
//        jPanel1.add(methode);
        adderPressed = true;
        jPanel1.revalidate();
         MainWindow.this.revalidate();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   

}
